"""Builds assets/js/answers/tz-countries.js: IANA time zone -> ISO country code,
from the tz database's zone.tab (shipped with Python's tzdata package).
Run: python tools/build_tz_countries.py
"""
import json, os, tzdata

base = os.path.join(os.path.dirname(tzdata.__file__), 'zoneinfo')
zones = {}
with open(os.path.join(base, 'zone.tab'), encoding='utf-8') as f:
    for line in f:
        if line.startswith('#') or not line.strip():
            continue
        code, _, zone = line.split('\t')[:3]
        zones[zone.strip()] = code
# Old names browsers still report.
for old, new in {'Europe/Belfast': 'GB', 'Asia/Calcutta': 'IN', 'Asia/Saigon': 'VN', 'Asia/Katmandu': 'NP',
                 'Asia/Rangoon': 'MM', 'America/Buenos_Aires': 'AR', 'Europe/Kiev': 'UA', 'US/Eastern': 'US',
                 'US/Central': 'US', 'US/Mountain': 'US', 'US/Pacific': 'US', 'Australia/Canberra': 'AU'}.items():
    zones.setdefault(old, new)
out = os.path.join(os.path.dirname(__file__), '..', 'assets', 'js', 'answers', 'tz-countries.js')
with open(out, 'w', encoding='utf-8', newline='\n') as f:
    f.write('// Time zone -> country (ISO 3166 code), from the tz database\'s zone.tab.\n')
    f.write('// Generated by tools/build_tz_countries.py; don\'t edit by hand.\n')
    f.write('export default ' + json.dumps(zones, separators=(',', ':'), sort_keys=True) + ';\n')
print(len(zones), 'zones')
